//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaksApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_CECHY
    {
        public GM_CECHY()
        {
            this.GM_WARTOSCI_CECH = new HashSet<GM_WARTOSCI_CECH>();
        }
    
        public int ID { get; set; }
        public string NAZWA { get; set; }
    
        public virtual ICollection<GM_WARTOSCI_CECH> GM_WARTOSCI_CECH { get; set; }
    }
}
