//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaksApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_PZ
    {
        public int ID { get; set; }
        public int MAGNUM { get; set; }
        public string KOD { get; set; }
        public System.DateTime DATA_WYSTAWIENIA { get; set; }
        public short ROK { get; set; }
        public short MIESIAC { get; set; }
        public int NR { get; set; }
        public string NUMER { get; set; }
        public Nullable<int> ID_FZ { get; set; }
        public short BLOKADA { get; set; }
        public int ID_DOSTAWCY { get; set; }
        public string NAZWA_SKROCONA_DOSTAWCY { get; set; }
        public string NIP_DOSTAWCY { get; set; }
        public string NAZWA_PELNA_DOSTAWCY { get; set; }
        public string ULICA_DOSTAWCY { get; set; }
        public string NRDOMU_DOSTAWCY { get; set; }
        public string NRLOKALU_DOSTAWCY { get; set; }
        public string KOD_DOSTAWCY { get; set; }
        public string MIEJSCOWOSC_DOSTAWCY { get; set; }
        public short ROLNIKR { get; set; }
        public string PANSTWO_DOSTAWCY { get; set; }
        public string KOD_KRESKOWY { get; set; }
        public string NAZWA_DOKUMENTU { get; set; }
        public string PESEL_DOSTAWCY { get; set; }
        public string NUMER_DOWODU_DOSTAWCY { get; set; }
        public Nullable<System.DateTime> DATA_DOWODU_DOSTAWCY { get; set; }
        public string ORGAN_DOWODU_DOSTAWCY { get; set; }
        public decimal WARTOSC_NETTO_ZAKUPU_PO { get; set; }
        public decimal KWOTA_VAT_ZAKUPU_PO { get; set; }
        public decimal WARTOSC_BRUTTO_ZAKUPU_PO { get; set; }
        public string NUMER_WZ_DOSTAWCY { get; set; }
        public string OPERATOR { get; set; }
        public System.DateTime DATAREJESTRACJI { get; set; }
        public string ZMIENIL { get; set; }
        public System.DateTime DATAZMIANY { get; set; }
        public short SPOSOB_LICZENIA { get; set; }
        public decimal WARTOSC_ROZRACHUNKU { get; set; }
        public string SYGNATURA { get; set; }
        public string ZNACZNIKI { get; set; }
        public Nullable<int> ID_WNT { get; set; }
        public byte[] UWAGI { get; set; }
        public string GUID { get; set; }
    
        public virtual GM_FZ GM_FZ { get; set; }
        public virtual R3_CONTACTS R3_CONTACTS { get; set; }
    }
}
