//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaksApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_WARTOSCI_CECH
    {
        public GM_WARTOSCI_CECH()
        {
            this.GM_TOWARY = new HashSet<GM_TOWARY>();
            this.GM_TOWARY1 = new HashSet<GM_TOWARY>();
            this.GM_TOWARY2 = new HashSet<GM_TOWARY>();
            this.GM_TOWARY3 = new HashSet<GM_TOWARY>();
            this.GM_TOWARY4 = new HashSet<GM_TOWARY>();
        }
    
        public int ID { get; set; }
        public int ID_CECHY { get; set; }
        public string KOD { get; set; }
        public string KOD_KRESKOWY { get; set; }
        public string NAZWA { get; set; }
    
        public virtual GM_CECHY GM_CECHY { get; set; }
        public virtual ICollection<GM_TOWARY> GM_TOWARY { get; set; }
        public virtual ICollection<GM_TOWARY> GM_TOWARY1 { get; set; }
        public virtual ICollection<GM_TOWARY> GM_TOWARY2 { get; set; }
        public virtual ICollection<GM_TOWARY> GM_TOWARY3 { get; set; }
        public virtual ICollection<GM_TOWARY> GM_TOWARY4 { get; set; }
    }
}
