//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaksApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class R3_CONTACT_ADDRESSES
    {
        public R3_CONTACT_ADDRESSES()
        {
            this.GM_FS = new HashSet<GM_FS>();
            this.GM_WZ = new HashSet<GM_WZ>();
            this.R3_CONTACTS1 = new HashSet<R3_CONTACTS>();
        }
    
        public int ID { get; set; }
        public string STREET { get; set; }
        public string APARTMENT_NUMBER { get; set; }
        public string PROVINCE { get; set; }
        public string ZIPCODE { get; set; }
        public int TYPE_ID { get; set; }
        public int CONTACT_ID { get; set; }
        public string PLACE { get; set; }
        public string COUNTRY { get; set; }
        public string BUILDING_NUMBER { get; set; }
        public int PERSON_ID { get; set; }
        public string POWIAT { get; set; }
        public string GMINA { get; set; }
        public string KOD_GMINY_WG_GUS { get; set; }
        public string POCZTA { get; set; }
        public string GLN { get; set; }
        public string C_IDENT { get; set; }
        public string M_IDENT { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> M_DATE { get; set; }
    
        public virtual ICollection<GM_FS> GM_FS { get; set; }
        public virtual ICollection<GM_WZ> GM_WZ { get; set; }
        public virtual R3_CONTACTS R3_CONTACTS { get; set; }
        public virtual ICollection<R3_CONTACTS> R3_CONTACTS1 { get; set; }
    }
}
