//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaksApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class R3_CONTACTS
    {
        public R3_CONTACTS()
        {
            this.GM_FS = new HashSet<GM_FS>();
            this.GM_FS1 = new HashSet<GM_FS>();
            this.GM_FS2 = new HashSet<GM_FS>();
            this.GM_FZ = new HashSet<GM_FZ>();
            this.GM_PZ = new HashSet<GM_PZ>();
            this.GM_TOWARY = new HashSet<GM_TOWARY>();
            this.GM_TOWARY1 = new HashSet<GM_TOWARY>();
            this.GM_WZ = new HashSet<GM_WZ>();
            this.GM_WZ1 = new HashSet<GM_WZ>();
            this.GM_WZ2 = new HashSet<GM_WZ>();
            this.R3_CONTACT_ADDRESSES = new HashSet<R3_CONTACT_ADDRESSES>();
            this.R3_CONTACT_PHONES = new HashSet<R3_CONTACT_PHONES>();
            this.R3_CONTACT_WEB_ADDRESSES = new HashSet<R3_CONTACT_WEB_ADDRESSES>();
        }
    
        public int ID { get; set; }
        public string SHORT_NAME { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public short CONTACT_TYPE { get; set; }
        public string TAXID { get; set; }
        public string APARTMENT_NUMBER { get; set; }
        public string PROVINCE { get; set; }
        public int DESCRIPTION_ID { get; set; }
        public Nullable<int> ADDRESS_ID { get; set; }
        public Nullable<int> INTERNAL_REVENUE_ID { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> CURRENCY_ID { get; set; }
        public short CANVASSER { get; set; }
        public short DELIVERER { get; set; }
        public short PURCHASER { get; set; }
        public string CANVASSER_ACCOUNT { get; set; }
        public string STREET { get; set; }
        public string FULL_NAME { get; set; }
        public string PLACE { get; set; }
        public string COUNTRY { get; set; }
        public string BUILDING_NUMBER { get; set; }
        public string ZIPCODE { get; set; }
        public System.DateTime C_DATE { get; set; }
        public Nullable<System.DateTime> M_DATE { get; set; }
        public string C_IDENT { get; set; }
        public string M_IDENT { get; set; }
        public string EU_CODE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string GUID { get; set; }
        public string POWIAT { get; set; }
        public string GMINA { get; set; }
        public string KOD_GMINY_WG_GUS { get; set; }
        public short ARCHIWALNY { get; set; }
        public string POCZTA { get; set; }
        public Nullable<int> ID_REGIONU { get; set; }
        public string GLN { get; set; }
    
        public virtual ICollection<GM_FS> GM_FS { get; set; }
        public virtual ICollection<GM_FS> GM_FS1 { get; set; }
        public virtual ICollection<GM_FS> GM_FS2 { get; set; }
        public virtual ICollection<GM_FZ> GM_FZ { get; set; }
        public virtual ICollection<GM_PZ> GM_PZ { get; set; }
        public virtual ICollection<GM_TOWARY> GM_TOWARY { get; set; }
        public virtual ICollection<GM_TOWARY> GM_TOWARY1 { get; set; }
        public virtual ICollection<GM_WZ> GM_WZ { get; set; }
        public virtual ICollection<GM_WZ> GM_WZ1 { get; set; }
        public virtual ICollection<GM_WZ> GM_WZ2 { get; set; }
        public virtual ICollection<R3_CONTACT_ADDRESSES> R3_CONTACT_ADDRESSES { get; set; }
        public virtual R3_CONTACT_ADDRESSES R3_CONTACT_ADDRESSES1 { get; set; }
        public virtual ICollection<R3_CONTACT_PHONES> R3_CONTACT_PHONES { get; set; }
        public virtual ICollection<R3_CONTACT_WEB_ADDRESSES> R3_CONTACT_WEB_ADDRESSES { get; set; }
    }
}
