//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaksApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GM_CECHY> GM_CECHY { get; set; }
        public DbSet<GM_FS> GM_FS { get; set; }
        public DbSet<GM_FZ> GM_FZ { get; set; }
        public DbSet<GM_PZ> GM_PZ { get; set; }
        public DbSet<GM_TOWARY> GM_TOWARY { get; set; }
        public DbSet<GM_WARTOSCI_CECH> GM_WARTOSCI_CECH { get; set; }
        public DbSet<GM_WZ> GM_WZ { get; set; }
        public DbSet<R3_CONTACT_ADDRESSES> R3_CONTACT_ADDRESSES { get; set; }
        public DbSet<R3_CONTACT_PHONES> R3_CONTACT_PHONES { get; set; }
        public DbSet<R3_CONTACT_WEB_ADDRESSES> R3_CONTACT_WEB_ADDRESSES { get; set; }
        public DbSet<R3_CONTACTS> R3_CONTACTS { get; set; }
    }
}
